version: 1.0.{build}

branches:
  only:
    - master
  
image:
#  - Visual Studio 2013
  - Visual Studio 2015

platform: x64

build:
  verbosity: normal

environment:
  matrix:
  - BOOST_VERSION: default
    CMAKE_OPTIONS: -DCMAKE_BUILD_TYPE=Debug
  - BOOST_VERSION: default
    CMAKE_OPTIONS: -DCMAKE_BUILD_TYPE=Release

install:
  ############################################################################
  # All the dependencies are installed in %APPVEYOR_BUILD_FOLDER%\deps
  ############################################################################
  - set DEPS_DIR=%APPVEYOR_BUILD_FOLDER%\deps
  - mkdir %DEPS_DIR%
  
  ############################################################################
  # Install Boost
  ############################################################################
  - set BOOST_ROOT=C:\Libraries\boost_1_58_0
 
  ############################################################################
  # Install Lz4
  ############################################################################
  - set LZ4_DIR=%DEPS_DIR%\lz4
  - set LZ4_URL="https://github.com/lz4/lz4.git"
  - cd %DEPS_DIR%
  - git clone --depth 1 --recursive --quiet %LZ4_URL% %LZ4_DIR%
  - cd %LZ4_DIR%
  - mkdir build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=%LZ4_ROOT%\build -DBUILD_STATIC_LIBS=on -g %APPVEYOR_BUILD_WORKER_IMAGE% -Ax64 ../contrib/cmake_unofficial
  - cmake --build .
  - cmake --build . --target install
  - set LZ4_ROOT=%LZ4_ROOT%\build

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - cmake -g %APPVEYOR_BUILD_WORKER_IMAGE% -Ax64 %CMAKE_OPTIONS% ..
